### ISSUE TITLE
[3.4.8] Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by ruudk** [kamilkisiela/graphql-inspector#2409]
### Issue workflow progress

Why are tags only published on NPM and not on GitHub? This makes it extremely hard to know that a new version was tagged/released. 
https://github.com/kamilkisiela/graphql-inspector/tags
https://www.npmjs.com/package/@graphql-inspector/cli

_Progress of the issue based on the
[Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Make sure to fork this template and run `pnpm generate` in the terminal.
     >
     > Please make sure the Codegen and plugins version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

After installing 3.4.8 I get this error:

```
$ npm --global --silent install @graphql-inspector/cli
$ graphql-inspector
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- /opt/homebrew/lib/node_modules/@graphql-inspector/cli/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/@graphql-inspector/cli/index.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/homebrew/lib/node_modules/@graphql-inspector/cli/index.js' ]
}

Node.js v18.15.0
```

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior**

No error

**Environment:**

- OS: macOS 13.2.1
- `@graphql-inspector/...`:
- `graphql`:
- NodeJS: v18.15.0

**Additional context**

**Comment by ruudk** [comment]
Turns out 3.4.7 has the same issue, but 3.4.6 works fine.

**Comment by fullyonline** [comment]
I stumbled into a different error, but ist's also missing a module. 

It worked with 3.4.6 and fails with the later versions.

Here's my error:

```
$ npx graphql-inspector diff git:origin/master:packages/client/schema.graphql schema.graphql            
node:internal/modules/cjs/loader:1050
  throw err;
  ^

Error: Cannot find module '@graphql-inspector/commands'
Require stack:
- client\node_modules\@graphql-inspector\cli\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (client\node_modules\@graphql-inspector\cli\index.js:8:18)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'client\\node_modules\\@graphql-inspector\\cli\\index.js'
  ]
}

Node.js v18.14.0
```

Environment:

Windows 10
NodeJS: v18.14.0

**Comment by TuvalSimha** [comment]
Hey @ruudk and @fullyonline,

First, thank you for this new open issue, it helps us a lot.
We had some problems with the release version flow,  you are more than welcome to try the new version `3.4.9`, everything should work just right.

Let me know if something is still broken. Thanks!

**Comment by fullyonline** [comment]
I can confirm, that the version `3.4.9` is working as expected. Thank you!

**Comment by ruudk** [comment]
Works, thank you very much 💙
